### ISSUE TITLE
Store pointer instead of flow id into bihash.

### ISSUE THREAD

**Issue by unixapple** [liudf0716/udpi#4]
https://github.com/liudf0716/udpi/blob/11ecf78e61442984d92d5551f83b521bc5721f87/src/dpi_node.c#L155

这里的代码将指针而不是flow_id的值存进了bihash，导致如果另外一向流查到flow结构时，将出现pool引用错误。

不过看起来udpi这个项目基本上没有人在维护了，我这里的场景是想做个简单的dpi脚手架，调试发现了这个问题。。。

**Comment by liudf0716** [comment]
@fortitudepub 也不是不维护，我问了intel的人，他们现在有针对这个的收费服务

**Comment by unixapple** [comment]
嗯，先close掉保存个记录，我本地改动太大，不好搞个mr了。
